### ISSUE TITLE
German Hypenation pattern

### ISSUE THREAD

**Issue by the42** [speedata/hyphenation#1]
Which hyphenation pattern file do I have to use from
http://ctan.math.utah.edu/ctan/tex-archive/language/hyph-utf8/tex/generic/hyph-utf8/patterns/txt/
to support german language?

Thank you!

**Comment by pgundlach** [comment]
`hyph-de-1901.pat.txt` or `hyph-de-1996.pat.txt` , depending if you need the old hyphenation rules or the new ones.
