### ISSUE TITLE
add license, go.mod file and tagged version to make documentation be displayed correctly

### ISSUE THREAD

**Issue by ilyapashuk** [speedata/hyphenation#2]
please add some opensource license, like mit and go.mod file to this repo and add a version tag, like v1.0

documentation on pkg.go.dev can't be displayed without this

**Comment by pgundlach** [comment]
I'll do so. Thanks for the issue!

**Comment by pgundlach** [comment]
Is it really necessary to add a `go.mod` file? Works fine here (Go 1.16) without `go.mod`.

**Comment by ilyapashuk** [comment]
what about docs on pkg.go.dev?

**Comment by pgundlach** [comment]
Docs on pkg.go.dev are now displaying correctly.

**Comment by pgundlach** [comment]
Added `go.mod` and a version number tag.
